drop database if exists rdb;
create database if not exists rdb;
use rdb;

CREATE TABLE `RMT_RAPIDMATE_INTERNAL_USER` (
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `FIRST_NAME` varchar(100) DEFAULT NULL,
  `LAST_NAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `IS_EMAIL_VERIFIED` tinyint(1) DEFAULT NULL,
  `MOBILE` varchar(100) DEFAULT NULL,
  `IS_MOBILE_VERIFIED` tinyint(1) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `AUTAAR` varchar(255) DEFAULT NULL,
  `ROLE_ID` tinyint(2) DEFAULT NULL,
  `CITY_ID` smallint DEFAULT NULL,
  `STATE_ID` smallint(11) DEFAULT NULL,
  `COUNTRY_ID` tinyint(3) DEFAULT NULL,
  `ADDRESS` text DEFAULT NULL,
  `SIRET_NO` varchar(50) DEFAULT NULL,
  `STATUS` tinyint(2) DEFAULT 1,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_VEHICLE_TYPE` (
  `ID` TINYINT(2) NOT NULL AUTO_INCREMENT PRIMARY KEY , 
  `VEHICLE_TYPE` VARCHAR(50) DEFAULT NULL,
  `VEHICLE_TYPE_DESC` VARCHAR(100) NOT NULL,
  `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_DELIVERY_BOY` (
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `EXT_ID` varchar(50) NOT NULL,
  `USERNAME` varchar(100) DEFAULT NULL,
  `FIRST_NAME` varchar(100) DEFAULT NULL,
  `LAST_NAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `EMAIL_VERIFICATION` varchar(200) DEFAULT NULL,
  `PHONE` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `AUTAAR` varchar(255) DEFAULT NULL,
  `ROLE_ID` int(11) DEFAULT NULL,
  `CITY_ID` int(11) DEFAULT NULL,
  `STATE_ID` int(11) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `ADDRESS` text DEFAULT NULL,
  `SIRET_NO` varchar(50) DEFAULT NULL,
  `VEHICLE_ID` int(11) DEFAULT NULL,
  `DRIVER_LICENCE_NO` varchar(100) DEFAULT NULL,
  `INSURANCE` varchar(100) DEFAULT NULL,
  `PASSPORT` varchar(100) DEFAULT NULL,
  `IDENTITY_CARD` varchar(255) DEFAULT NULL,
  `COMPANY_NAME` varchar(100) DEFAULT NULL,
  `INDUSTRY` varchar(100) DEFAULT NULL,
  `DESCRIPTION` text DEFAULT NULL,
  `TERM_COND1` int(11) DEFAULT 0,
  `TERM_COND2` int(11) DEFAULT 0,
  `ACCOUNT_TYPE` enum('individual','company') DEFAULT 'individual' COMMENT 'individual: Account for individual customers, company: Account for corporate customers',
  `ACTIVE` int(11) DEFAULT 1,
  `OTP` varchar(100) DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RMT_DELIVERY_BOY_OTP(
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `OTP` varchar(100) DEFAULT NULL,
  `STATUS` TINYINT(1) DEFAULT 0, -- 0 PENDING, 1 VERIFIED, 2 EXPIRED
  `DELIVERY_BOY_ID` BIGINT NOT NULL,
  `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP

);

DROP TABLE IF EXISTS RMT_VEHICLE;
CREATE TABLE `RMT_VEHICLE` (
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `DELIVERY_BOY_ID` int(11) NOT NULL,
  `VEHICLE_TYPE_ID` TINYINT(2) DEFAULT NULL,
  `PLAT_NO` varchar(100) DEFAULT NULL,
  `MODAL` varchar(100) DEFAULT NULL,
  `VEHICLE_FRONT_PHOTO` varchar(255) DEFAULT NULL,
  `VEHICLE_BACK_PHOTO` varchar(255) DEFAULT NULL,
  `RCV_NO` varchar(255) DEFAULT NULL,
  `RCV_PHOTO` varchar(255) DEFAULT NULL,
  `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`VEHICLE_TYPE_ID`) REFERENCES `RMT_VEHICLE_TYPE` (`ID`)
);

CREATE TABLE `RMT_DELIVERY_BOY_WALLET` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `DELIVERY_BOY_ID` int(11) DEFAULT NULL,
  `BALANCE` decimal(10,2) NOT NULL DEFAULT 0.00,
  `CURRENCY` varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_DELIVERY_BOY_ACCOUNT` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `DELIVERY_BOY_ID` int(11) DEFAULT NULL,
	 `ACCOUNT_NUMBER`  VARCHAR(16) NOT NULL,
	`BANK_NAME` VARCHAR(50) NOT NULL,
	`IFSC` VARCHAR(20) NOT NULL,
	`ADDRESS`  VARCHAR(255) NOT NULL,
  `CURRENCY` varchar(11) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_DELIVERY_BOY_PAYMENT_CARD` (
    `ID` INT PRIMARY KEY AUTO_INCREMENT,
	  `DELIVERY_BOY_ID` int(11) DEFAULT NULL,
    `CARD_NUMBER` VARCHAR(16) NOT NULL,
    `CARD_HOLDER_NAME` VARCHAR(100) NOT NULL,
    `EXPIRATION_DATE` DATE NOT NULL,
    `CVV` VARCHAR(4) NOT NULL,
    `BILLING_ADDRESS` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
     `IS_DEL` TINYINT(1) DEFAULT 0,
    `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
    `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE RMT_CONSUMER (
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
   `EXT_ID` varchar(50) NOT NULL,
   `USERNAME` varchar(100) DEFAULT NULL,
  `FIRST_NAME` varchar(100) DEFAULT NULL,
  `LAST_NAME` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `EMAIL_VERIFICATION` varchar(200) DEFAULT NULL,
  `PHONE` varchar(100) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  `AUTAAR` varchar(255) DEFAULT NULL,
  `ROLE_ID` int(11) DEFAULT NULL,
  `CITY_ID` int(11) DEFAULT NULL,
  `STATE_ID` int(11) DEFAULT NULL,
  `COUNTRY_ID` int(11) DEFAULT NULL,
  `ADDRESS` text DEFAULT NULL,
  `SIRET_NO` varchar(50) DEFAULT NULL,
  `VEHICLE_ID` int(11) DEFAULT NULL,
  `DRIVER_LICENCE_NO` varchar(100) DEFAULT NULL,
  `INSURANCE` varchar(100) DEFAULT NULL,
  `PASSPORT` varchar(100) DEFAULT NULL,
  `IDENTITY_CARD` varchar(255) DEFAULT NULL,
  `COMPANY_NAME` varchar(100) DEFAULT NULL,
  `INDUSTRY` varchar(100) DEFAULT NULL,
  `DESCRIPTION` text DEFAULT NULL,
  `TERM_COND1` int(11) DEFAULT 0,
  `TERM_COND2` int(11) DEFAULT 0,
  `ACCOUNT_TYPE` enum('INDIVIDUAL','COMPANY') DEFAULT 'INDIVIDUAL' COMMENT 'individual: Account for individual customers, company: Account for corporate customers',
  `STATUS` TINYINT(1) DEFAULT 1,
  `OTP` varchar(100) DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_TRANSACTION` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `WALLET_ID` int(11) DEFAULT NULL,
  `USER_ID` int(11) DEFAULT NULL,
  `TYPE` enum('credit','debit') DEFAULT NULL,
  `AMOUNT` decimal(10,2) DEFAULT NULL,
  `CURRENCY` varchar(10) NOT NULL,
  `DESCRIPTION` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_PAYMENT` (
    `PAYMENT_ID` INT PRIMARY KEY AUTO_INCREMENT,
    `TRANSACTION_ID` INT NOT NULL,
    `USER_ID` INT NOT NULL,
    `WALLET_ID` INT DEFAULT NULL,
    `AMOUNT` DECIMAL(10, 2) NOT NULL,
    `CURRENCY` VARCHAR(10) NOT NULL,
    `PAYMENT_METHOD` VARCHAR(50) NOT NULL,
    `PAYMENT_STATUS` ENUM('Pending', 'Completed', 'Failed') NOT NULL,
    `DESCRIPTION` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
     `IS_DEL` TINYINT(1) DEFAULT 0,
    `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
    `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`TRANSACTION_ID`) REFERENCES `RMT_TRANSACTION` (`ID`)
);

CREATE TABLE `RMT_FAQ` (
    `FAQ_ID` INT PRIMARY KEY AUTO_INCREMENT,
    `QUESTION` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    `ANSWER` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
     `IS_DEL` TINYINT(1) DEFAULT 0,
    `CATEGORY` VARCHAR(100) DEFAULT NULL,
    `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
    `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_ACCOUNT_TYPE` (
    `ACCOUNT_TYPE_ID` INT PRIMARY KEY AUTO_INCREMENT,
    `ACCOUNT_TYPE_NAME` VARCHAR(100) NOT NULL,
    `DESCRIPTION` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
     `IS_DEL` TINYINT(1) DEFAULT 0,
    `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
    `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_SERVICE` (
  `ID` TINYINT(1) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `SERVICE_NAME` VARCHAR(100) NOT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO RMT_SERVICE(SERVICE_NAME) VALUES('PICKUP-DROPOFF'), ('SCHEDULED');

DROP TABLE IF EXISTS RMT_LOCATION;
CREATE TABLE `RMT_LOCATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `LOCATION_NAME` varchar(100) NOT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `CITY` varchar(50) DEFAULT NULL,
  `STATE` varchar(50) DEFAULT NULL,
  `POSTAL_CODE` varchar(20) DEFAULT NULL,
  `COUNTRY` varchar(50) DEFAULT NULL,
  `LATITUDE` decimal(10,8) DEFAULT NULL,
  `LONGITUDE` decimal(11,8) DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

DROP TABLE  IF EXISTS RMT_ORDER;
CREATE TABLE `RMT_ORDER` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ORDER_NUMBER` varchar(20) NOT NULL,
  `CONSUMER_ID`  BIGINT NOT NULL,
  `DELIVERY_BOY_ID` BIGINT NOT NULL,
  `SERVICE_TYPE_ID` TINYINT(1) NOT NULL,
  `VEHICLE_TYPE_ID` TINYINT(2) NOT NULL,
  `ORDER_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `PICKUP_LOCATION_ID` int(11) DEFAULT NULL,
  `DROPOFF_LOCATION_ID` int(11) DEFAULT NULL,
  `SHIFT_START_TIME` time NULL,
  `SHIFT_END_TIME` time NULL,
  `ORDER_STATUS` enum('ORDER_PLACED', 'CONIRMED', 'PAYMENT_FAILED', 'ORDER_ACCEPTED', 'ORDER_REJECTED', 'ON_THE_WAY_PICKUP', 'PICKUP_COMPLETED', 'ON_THE_WAY_DROP_OFF', 'COMPLETED', 'CANCELLED') DEFAULT 'ORDER_PLACED',
  `DELIVERY_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`CONSUMER_ID`) REFERENCES `RMT_CONSUMER`(`ID`),
  FOREIGN KEY (`DELIVERY_BOY_ID`) REFERENCES `RMT_DELIVERY_BOY`(`ID`),
  FOREIGN KEY (`PICKUP_LOCATION_ID`) REFERENCES `RMT_LOCATION`(`ID`),
  FOREIGN KEY (`DROPOFF_LOCATION_ID`) REFERENCES `RMT_LOCATION`(`ID`),
  FOREIGN KEY (`SERVICE_TYPE_ID`) REFERENCES `RMT_SERVICE`(`ID`),
  FOREIGN KEY (`VEHICLE_TYPE_ID`) REFERENCES `RMT_VEHICLE_TYPE` (`ID`)
);

CREATE TABLE `RMT_TRACK_ORDER` (
  `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `ORDER_NUMBER` VARCHAR(50) NOT NULL,
  `DELIVERY_BOY_ID` BIGINT NOT NULL,
  `STATUS` ENUM('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled') NOT NULL,
  `TOTAL_AMOUNT` DECIMAL(10, 2) NOT NULL,
  `CURRENCY` VARCHAR(10) NOT NULL,
  `SHIPPING_ADDRESS` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `ORDER_DATE` DATE NOT NULL,
  `EXPECTED_DELIVERY_DATE` DATE,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'ADMIN',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'ADMIN',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`DELIVERY_BOY_ID`) REFERENCES `RMT_DELIVERY_BOY`(`ID`)
);

CREATE TABLE `RMT_ORDER_DOCUMENT` (
    `DOCUMENT_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `DOCUMENT_TYPE` ENUM('Invoice', 'Receipt', 'Contract', 'Shipping_Label', 'Custom') NOT NULL,
    `DOCUMENT_NAME` VARCHAR(255) NULL,
    `DOCUMENT_PATH` VARCHAR(255) NOT NULL,
     `IS_DEL` TINYINT(1) DEFAULT 0,
     `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_REFUND` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID` BIGINT NOT NULL,
    `REFUND_DATE` DATE NOT NULL,
    `AMOUNT` DECIMAL(10, 2) NOT NULL,
    `CURRENCY` VARCHAR(10) NOT NULL,
    `REASON` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    `STATUS` ENUM('Requested', 'Processing', 'Approved', 'Rejected') NOT NULL,
     `IS_DEL` TINYINT(1) DEFAULT 0,
    `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
    `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ORDER_ID`) REFERENCES `RMT_ORDER` (`ID`)
);

CREATE TABLE `RMT_RATING` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID` BIGINT NOT NULL,
    `CONSUMER_ID` BIGINT NOT NULL,
    `RATING` DECIMAL(3, 1) NOT NULL,
    `COMMENT` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
     `IS_DEL` TINYINT(1) DEFAULT 0,
    `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
    `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`ORDER_ID`) REFERENCES `RMT_ORDER` (`ID`),
    FOREIGN KEY (`CONSUMER_ID`) REFERENCES `RMT_CONSUMER` (`ID`)
);

CREATE TABLE `RMT_NOTIFICATION` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `CONSUMER_ID` BIGINT NOT NULL,
    `NOTIFICATION_TYPE` ENUM('Email', 'SMS', 'Push') NOT NULL,
    `MESSAGE` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    `IS_READ` BOOLEAN DEFAULT FALSE,
     `IS_DEL` TINYINT(1) DEFAULT 0,
    `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
    `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
    `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`CONSUMER_ID`) REFERENCES `RMT_CONSUMER` (`ID`)
);


CREATE TABLE `RMT_ENTERPRISE` (
    `ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `ENTERPRISE_NAME` VARCHAR(100) NOT NULL,
    `ADDRESS` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci,
    `CITY` VARCHAR(50),
    `STATE` VARCHAR(50),
    `COUNTRY` VARCHAR(50),
    `POSTAL_CODE` VARCHAR(20),
    `PHONE_NUMBER` VARCHAR(20),
    `EMAIL` VARCHAR(100),
    `WEBSITE` VARCHAR(100),
    `INDUSTRY` VARCHAR(100),
    `FOUNDED_DATE` DATE,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_WORK_ORDER` (
  `ID` BIGint NOT NULL AUTO_INCREMENT,
  `ORDER_ID` BIGint NOT NULL,
  `WORK_TYPE` enum('maintenance','repair','installation') DEFAULT 'maintenance',
  `STATUS` enum('Pending','InProgress','Completed','Cancelled') DEFAULT 'Pending',
  `SCHEDULED_DATE` date DEFAULT NULL,
  `SCHEDULED_TIME` time DEFAULT NULL,
  `COMPLETION_DATE` date DEFAULT NULL,
  `COMPLETION_TIME` time DEFAULT NULL,
  `NOTES` text DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`ORDER_ID`) REFERENCES `RMT_ORDER`(`ID`)
  );

CREATE TABLE `RMT_COUPON_CODE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(50) NOT NULL,
  `DISCOUNT` decimal(10,2) NOT NULL,
  `EXPIRY_DATE` date NOT NULL,
  `MAX_USAGE` int(11) DEFAULT 0,
  `CURRENT_USAGE` int(11) DEFAULT 0,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_code` (`code`)
);


CREATE TABLE `RMT_COUNTRY` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `COUNTRY_NAME` VARCHAR(100) NOT NULL,
  `COUNTRY_CODE` CHAR(3) NOT NULL,
  `AREA` DECIMAL(15, 2) DEFAULT NULL,
  `CAPITAL` VARCHAR(100) DEFAULT NULL,
  `REGION` VARCHAR(100) DEFAULT NULL,
  `SUBREGION` VARCHAR(100) DEFAULT NULL,
  `OFFICIAL_LANGUAGES` VARCHAR(255) DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `RMT_STATE` (
  `ID` INT PRIMARY KEY AUTO_INCREMENT,
  `STATE_NAME` VARCHAR(100) NOT NULL,
  `STATE_CODE` VARCHAR(10) NOT NULL,
  `COUNTRY_ID` INT NOT NULL,
  `AREA` DECIMAL(15, 2) DEFAULT NULL,
  `CAPITAL` VARCHAR(100) DEFAULT NULL,
  `REGION` VARCHAR(100) DEFAULT NULL,
  `SUBREGION` VARCHAR(100) DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`COUNTRY_ID`) REFERENCES `RMT_COUNTRY` (`ID`)
);


CREATE TABLE `RMT_CITY` (
  `CITY_ID` INT PRIMARY KEY AUTO_INCREMENT,
  `CITY_NAME` VARCHAR(100) NOT NULL,
  `STATE_ID` INT NOT NULL,
  `COUNTRY_ID` INT NOT NULL,
  `AREA` DECIMAL(15, 2) DEFAULT NULL,
  `CAPITAL` BOOLEAN DEFAULT FALSE,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`STATE_ID`) REFERENCES `RMT_STATE` (`ID`),
  FOREIGN KEY (`COUNTRY_ID`) REFERENCES `RMT_COUNTRY` (`ID`)
);

CREATE TABLE `RMT_CHAT` (
  `CHAT_ID` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `CONVERSATION_ID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `CONTENT` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `MESSAGE_TYPE` enum('text','voice') NOT NULL,
 `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP
);

---------------- ---------------- ---------------- ---------------- ---------------- ---------------- 
---------------- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX NEED TO VERIFY           XXXXXXXXXXXXXXXXXXXXXXXXXXXX
---------------- XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX DONT EXECUTE BELOW QUERY XXXXXXXXXXXXXXXXXXXXXXXXXXXX
---------------- ---------------- ---------------- ---------------- ---------------- ---------------- 


CREATE TABLE `RMT_PLANNING` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DELIVERY_ID` int(11) NOT NULL,
  `PLAN_TYPE_ID` int(11) NOT NULL,
  `SERVICE_TYPE_ID` int(11) NOT NULL,
  `VEHICLE_ID` int(11) NOT NULL,
  `PICKUP_LOCATION_ID` int(11) DEFAULT NULL,
  `DROPOFF_LOCATION_ID` int(11) DEFAULT NULL,
  `PICKUP_DATE` date NOT NULL,
  `PICKUP_TIME` time NOT NULL,
  `IS_REPEAT` tinyint(1) DEFAULT 0,
  `REPEAT_TYPE` enum('Daily','Weekly','Monthly') DEFAULT NULL,
  `REPEAT_DAY` int(11) DEFAULT NULL,
  `REPEAT_TILL` date DEFAULT NULL,
  `REPEAT_DAY_EXCEPTION` text DEFAULT NULL,
  `REPEAT_ON_DAY` enum('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday') DEFAULT NULL,
  `REPEAT_ON_THE` enum('First','Second','Third','Fourth','Last') DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `RMT_CONSUMER`(`USER_ID`),
  FOREIGN KEY (`PLAN_TYPE_ID`) REFERENCES `RMT_PLANNING_SLOT`(`ID`),
  FOREIGN KEY (`SERVICE_TYPE_ID`) REFERENCES `RMT_SERVICE`(`ID`),
  FOREIGN KEY (`VEHICLE_ID`) REFERENCES `RMT_VECHILE`(`ID`),
  FOREIGN KEY (`PICKUP_LOCATION_ID`) REFERENCES `RMT_LOCATION`(`ID`),
  FOREIGN KEY (`DROPOFF_LOCATION_ID`) REFERENCES `RMT_LOCATION`(`ID`)
);


--
-- Table structure for table `RMT_PLANNING_SLOT`
--

CREATE TABLE `RMT_PLANNING_SLOT` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `PLAN_NAME` varchar(100) NOT NULL,
  `PLAN_DESCRIPTION` text DEFAULT NULL,
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
);


--
-- Table structure for table `RMT_DEFAULT_PLANNING_CONFIGURATION`
--

CREATE TABLE `RMT_DEFAULT_PLANNING_CONFIGURATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLAN_TYPE_ID` int(11) NOT NULL,
  `SERVICE_TYPE_ID` int(11) NOT NULL,
  `PICKUP_LOCATION_ID` int(11) DEFAULT NULL,
  `DROPOFF_LOCATION_ID` int(11) DEFAULT NULL,
  `DEFAULT_PICKUP_TIME` time NOT NULL,
  `IS_REPEATABLE` tinyint(1) NOT NULL DEFAULT 0,
  `REPEAT_INTERVAL` int(11) DEFAULT NULL,  
   `IS_DEL` TINYINT(1) DEFAULT 0,
  `CREATED_BY` VARCHAR(100) DEFAULT 'USER',
  `CREATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` VARCHAR(100) DEFAULT 'USER',
  `UPDATED_ON` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`PLAN_TYPE_ID`) REFERENCES `RMT_PLANNING_SLOT`(`ID`),
  FOREIGN KEY (`SERVICE_TYPE_ID`) REFERENCES `RMT_SERVICE`(`ID`),
  FOREIGN KEY (`PICKUP_LOCATION_ID`) REFERENCES `RMT_LOCATION`(`ID`),
  FOREIGN KEY (`DROPOFF_LOCATION_ID`) REFERENCES `RMT_LOCATION`(`ID`)
);
