const RESPONSE_STATUS = Object.freeze({
    INVALID_ORDER_NUMBER: { CODE: "1001", STATUS_CODE : 404 , STATUS : "BAD_REQUEST"},
    UNABLE_TO_UPDATE_ORDER_STATUS: { CODE: "1002", STATUS_CODE : 500 , STATUS : "INTERNAL_SERVER_ERROR"},
    ORDER_STATUS_UPDATED_SUCCESSFULLY: { CODE: "1003", STATUS_CODE : 202 , STATUS : "ACCEPTED"},
});

global.RESPONSE_STATUS = RESPONSE_STATUS;