name: Deploy to Server

on:
  push:
    branches:
      - UAT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to Server
        run: |
          ssh -i "rapidmate-web-server.pem" ubuntu@ec2-16-171-224-246.eu-north-1.compute.amazonaws.com "sudo && ./deploy.sh"
